package se.diabol.scrolls


class GitHubData {

    // This data set is from a sample GitHub project, with some stuff replaced to match the unit test
    static def pullData = [
            [
                    "url"                : "https://api.github.com/repos/JohnJohnson/JohnsRepo/pulls/1",
                    "id"                 : 89797769,
                    "html_url"           : "https://github.com/JohnJohnson/JohnsRepo/pull/1",
                    "diff_url"           : "https://github.com/JohnJohnson/JohnsRepo/pull/1.diff",
                    "patch_url"          : "https://github.com/JohnJohnson/JohnsRepo/pull/1.patch",
                    "issue_url"          : "https://api.github.com/repos/JohnJohnson/JohnsRepo/issues/1",
                    "number"             : 1,
                    "state"              : "open",
                    "locked"             : false,
                    "title"              : "First Pull Request",
                    "user"               : [
                            "login"              : "JohnJohnson",
                            "id"                 : 20211364,
                            "avatar_url"         : "https://avatars.githubusercontent.com/u/20211364?v=3",
                            "gravatar_id"        : "",
                            "url"                : "https://api.github.com/users/JohnJohnson",
                            "html_url"           : "https://github.com/JohnJohnson",
                            "followers_url"      : "https://api.github.com/users/JohnJohnson/followers",
                            "following_url"      : "https://api.github.com/users/JohnJohnson/following{/other_user}",
                            "gists_url"          : "https://api.github.com/users/JohnJohnson/gists{/gist_id}",
                            "starred_url"        : "https://api.github.com/users/JohnJohnson/starred{/owner}{/repoWithPullRequests}",
                            "subscriptions_url"  : "https://api.github.com/users/JohnJohnson/subscriptions",
                            "organizations_url"  : "https://api.github.com/users/JohnJohnson/orgs",
                            "repos_url"          : "https://api.github.com/users/JohnJohnson/repos",
                            "events_url"         : "https://api.github.com/users/JohnJohnson/events{/privacy}",
                            "received_events_url": "https://api.github.com/users/JohnJohnson/received_events",
                            "type"               : "User",
                            "site_admin"         : false
                    ],
                    "body"               : "",
                    "created_at"         : "2016-10-18T11:39:29Z",
                    "updated_at"         : "2016-10-18T11:39:29Z",
                    "closed_at"          : null,
                    "merged_at"          : null,
                    "merge_commit_sha"   : "4c7006162d92fc79374737aea92426e9e56acd22",
                    "assignee"           : null,
                    "assignees"          : [],
                    "milestone"          : null,
                    "commits_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/pulls/1/commits",
                    "review_comments_url": "https://api.github.com/repos/JohnJohnson/JohnsRepo/pulls/1/comments",
                    "review_comment_url" : "https://api.github.com/repos/JohnJohnson/JohnsRepo/pulls/comments{/number}",
                    "comments_url"       : "https://api.github.com/repos/JohnJohnson/JohnsRepo/issues/1/comments",
                    "statuses_url"       : "https://api.github.com/repos/JohnJohnson/JohnsRepo/statuses/9fced306f95d6d059b0fe6c1b678fe17f242d6fc",
                    "head"               : [
                            "label": "JohnJohnson:some-branch",
                            "ref"  : "some-branch",
                            "sha"  : "9fced306f95d6d059b0fe6c1b678fe17f242d6fc",
                            "user" : [
                                    "login"              : "JohnJohnson",
                                    "id"                 : 20211364,
                                    "avatar_url"         : "https://avatars.githubusercontent.com/u/20211364?v=3",
                                    "gravatar_id"        : "",
                                    "url"                : "https://api.github.com/users/JohnJohnson",
                                    "html_url"           : "https://github.com/JohnJohnson",
                                    "followers_url"      : "https://api.github.com/users/JohnJohnson/followers",
                                    "following_url"      : "https://api.github.com/users/JohnJohnson/following{/other_user}",
                                    "gists_url"          : "https://api.github.com/users/JohnJohnson/gists{/gist_id}",
                                    "starred_url"        : "https://api.github.com/users/JohnJohnson/starred{/owner}{/repoWithPullRequests}",
                                    "subscriptions_url"  : "https://api.github.com/users/JohnJohnson/subscriptions",
                                    "organizations_url"  : "https://api.github.com/users/JohnJohnson/orgs",
                                    "repos_url"          : "https://api.github.com/users/JohnJohnson/repos",
                                    "events_url"         : "https://api.github.com/users/JohnJohnson/events{/privacy}",
                                    "received_events_url": "https://api.github.com/users/JohnJohnson/received_events",
                                    "type"               : "User",
                                    "site_admin"         : false
                            ],
                            "repoWithPullRequests" : [
                                    "id"               : 68914460,
                                    "name"             : "JohnsRepo",
                                    "full_name"        : "JohnJohnson/JohnsRepo",
                                    "owner"            : [
                                            "login"              : "JohnJohnson",
                                            "id"                 : 20211364,
                                            "avatar_url"         : "https://avatars.githubusercontent.com/u/20211364?v=3",
                                            "gravatar_id"        : "",
                                            "url"                : "https://api.github.com/users/JohnJohnson",
                                            "html_url"           : "https://github.com/JohnJohnson",
                                            "followers_url"      : "https://api.github.com/users/JohnJohnson/followers",
                                            "following_url"      : "https://api.github.com/users/JohnJohnson/following{/other_user}",
                                            "gists_url"          : "https://api.github.com/users/JohnJohnson/gists{/gist_id}",
                                            "starred_url"        : "https://api.github.com/users/JohnJohnson/starred{/owner}{/repoWithPullRequests}",
                                            "subscriptions_url"  : "https://api.github.com/users/JohnJohnson/subscriptions",
                                            "organizations_url"  : "https://api.github.com/users/JohnJohnson/orgs",
                                            "repos_url"          : "https://api.github.com/users/JohnJohnson/repos",
                                            "events_url"         : "https://api.github.com/users/JohnJohnson/events{/privacy}",
                                            "received_events_url": "https://api.github.com/users/JohnJohnson/received_events",
                                            "type"               : "User",
                                            "site_admin"         : false
                                    ],
                                    "private"          : false,
                                    "html_url"         : "https://github.com/JohnJohnson/JohnsRepo",
                                    "description"      : "Truly, just playing around with Jenkinsfile and pipelines",
                                    "fork"             : false,
                                    "url"              : "https://api.github.com/repos/JohnJohnson/JohnsRepo",
                                    "forks_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/forks",
                                    "keys_url"         : "https://api.github.com/repos/JohnJohnson/JohnsRepo/keys{/key_id}",
                                    "collaborators_url": "https://api.github.com/repos/JohnJohnson/JohnsRepo/collaborators{/collaborator}",
                                    "teams_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/teams",
                                    "hooks_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/hooks",
                                    "issue_events_url" : "https://api.github.com/repos/JohnJohnson/JohnsRepo/issues/events{/number}",
                                    "events_url"       : "https://api.github.com/repos/JohnJohnson/JohnsRepo/events",
                                    "assignees_url"    : "https://api.github.com/repos/JohnJohnson/JohnsRepo/assignees{/user}",
                                    "branches_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/branches{/branch}",
                                    "tags_url"         : "https://api.github.com/repos/JohnJohnson/JohnsRepo/tags",
                                    "blobs_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/git/blobs{/sha}",
                                    "git_tags_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/git/tags{/sha}",
                                    "git_refs_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/git/refs{/sha}",
                                    "trees_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/git/trees{/sha}",
                                    "statuses_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/statuses/{sha}",
                                    "languages_url"    : "https://api.github.com/repos/JohnJohnson/JohnsRepo/languages",
                                    "stargazers_url"   : "https://api.github.com/repos/JohnJohnson/JohnsRepo/stargazers",
                                    "contributors_url" : "https://api.github.com/repos/JohnJohnson/JohnsRepo/contributors",
                                    "subscribers_url"  : "https://api.github.com/repos/JohnJohnson/JohnsRepo/subscribers",
                                    "subscription_url" : "https://api.github.com/repos/JohnJohnson/JohnsRepo/subscription",
                                    "commits_url"      : "https://api.github.com/repos/JohnJohnson/JohnsRepo/commits{/sha}",
                                    "git_commits_url"  : "https://api.github.com/repos/JohnJohnson/JohnsRepo/git/commits{/sha}",
                                    "comments_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/comments{/number}",
                                    "issue_comment_url": "https://api.github.com/repos/JohnJohnson/JohnsRepo/issues/comments{/number}",
                                    "contents_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/contents/{+path}",
                                    "compare_url"      : "https://api.github.com/repos/JohnJohnson/JohnsRepo/compare/{base}...{head}",
                                    "merges_url"       : "https://api.github.com/repos/JohnJohnson/JohnsRepo/merges",
                                    "archive_url"      : "https://api.github.com/repos/JohnJohnson/JohnsRepo/{archive_format}{/ref}",
                                    "downloads_url"    : "https://api.github.com/repos/JohnJohnson/JohnsRepo/downloads",
                                    "issues_url"       : "https://api.github.com/repos/JohnJohnson/JohnsRepo/issues{/number}",
                                    "pulls_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/pulls{/number}",
                                    "milestones_url"   : "https://api.github.com/repos/JohnJohnson/JohnsRepo/milestones{/number}",
                                    "notifications_url": "https://api.github.com/repos/JohnJohnson/JohnsRepo/notifications{?since,all,participating}",
                                    "labels_url"       : "https://api.github.com/repos/JohnJohnson/JohnsRepo/labels{/name}",
                                    "releases_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/releases{/id}",
                                    "deployments_url"  : "https://api.github.com/repos/JohnJohnson/JohnsRepo/deployments",
                                    "created_at"       : "2016-09-22T11:25:05Z",
                                    "updated_at"       : "2016-10-18T11:14:28Z",
                                    "pushed_at"        : "2016-10-18T11:39:29Z",
                                    "git_url"          : "git://github.com/JohnJohnson/JohnsRepo.git",
                                    "ssh_url"          : "git@github.com:JohnJohnson/JohnsRepo.git",
                                    "clone_url"        : "https://github.com/JohnJohnson/JohnsRepo.git",
                                    "svn_url"          : "https://github.com/JohnJohnson/JohnsRepo",
                                    "homepage"         : null,
                                    "size"             : 4,
                                    "stargazers_count" : 0,
                                    "watchers_count"   : 0,
                                    "language"         : null,
                                    "has_issues"       : false,
                                    "has_downloads"    : true,
                                    "has_wiki"         : false,
                                    "has_pages"        : false,
                                    "forks_count"      : 0,
                                    "mirror_url"       : null,
                                    "open_issues_count": 1,
                                    "forks"            : 0,
                                    "open_issues"      : 1,
                                    "watchers"         : 0,
                                    "default_branch"   : "master"
                            ]
                    ],
                    "base"               : [
                            "label"            : "JohnJohnson:master",
                            "ref"              : "master",
                            "sha"              : "a2b43f995ee7b23fde7911b7580e2addd860329a",
                            "user"             : [
                                    "login"              : "JohnJohnson",
                                    "id"                 : 20211364,
                                    "avatar_url"         : "https://avatars.githubusercontent.com/u/20211364?v=3",
                                    "gravatar_id"        : "",
                                    "url"                : "https://api.github.com/users/JohnJohnson",
                                    "html_url"           : "https://github.com/JohnJohnson",
                                    "followers_url"      : "https://api.github.com/users/JohnJohnson/followers",
                                    "following_url"      : "https://api.github.com/users/JohnJohnson/following{/other_user}",
                                    "gists_url"          : "https://api.github.com/users/JohnJohnson/gists{/gist_id}",
                                    "starred_url"        : "https://api.github.com/users/JohnJohnson/starred{/owner}{/repoWithPullRequests}",
                                    "subscriptions_url"  : "https://api.github.com/users/JohnJohnson/subscriptions",
                                    "organizations_url"  : "https://api.github.com/users/JohnJohnson/orgs",
                                    "repos_url"          : "https://api.github.com/users/JohnJohnson/repos",
                                    "events_url"         : "https://api.github.com/users/JohnJohnson/events{/privacy}",
                                    "received_events_url": "https://api.github.com/users/JohnJohnson/received_events",
                                    "type"               : "User",
                                    "site_admin"         : false
                            ],
                            "repoWithPullRequests"             : [],
                            "id"               : 68914460,
                            "name"             : "JohnsRepo",
                            "full_name"        : "JohnJohnson/JohnsRepo",
                            "owner"            : [
                                    "login"              : "JohnJohnson",
                                    "id"                 : 20211364,
                                    "avatar_url"         : "https://avatars.githubusercontent.com/u/20211364?v=3",
                                    "gravatar_id"        : "",
                                    "url"                : "https://api.github.com/users/JohnJohnson",
                                    "html_url"           : "https://github.com/JohnJohnson",
                                    "followers_url"      : "https://api.github.com/users/JohnJohnson/followers",
                                    "following_url"      : "https://api.github.com/users/JohnJohnson/following{/other_user}",
                                    "gists_url"          : "https://api.github.com/users/JohnJohnson/gists{/gist_id}",
                                    "starred_url"        : "https://api.github.com/users/JohnJohnson/starred{/owner}{/repoWithPullRequests}",
                                    "subscriptions_url"  : "https://api.github.com/users/JohnJohnson/subscriptions",
                                    "organizations_url"  : "https://api.github.com/users/JohnJohnson/orgs",
                                    "repos_url"          : "https://api.github.com/users/JohnJohnson/repos",
                                    "events_url"         : "https://api.github.com/users/JohnJohnson/events{/privacy}",
                                    "received_events_url": "https://api.github.com/users/JohnJohnson/received_events",
                                    "type"               : "User",
                                    "site_admin"         : false
                            ],
                            "private"          : false,
                            "html_url"         : "https://github.com/JohnJohnson/JohnsRepo",
                            "description"      : "Truly, just playing around with Jenkinsfile and pipelines",
                            "fork"             : false,
                            "url"              : "https://api.github.com/repos/JohnJohnson/JohnsRepo",
                            "forks_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/forks",
                            "keys_url"         : "https://api.github.com/repos/JohnJohnson/JohnsRepo/keys{/key_id}",
                            "collaborators_url": "https://api.github.com/repos/JohnJohnson/JohnsRepo/collaborators{/collaborator}",
                            "teams_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/teams",
                            "hooks_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/hooks",
                            "issue_events_url" : "https://api.github.com/repos/JohnJohnson/JohnsRepo/issues/events{/number}",
                            "events_url"       : "https://api.github.com/repos/JohnJohnson/JohnsRepo/events",
                            "assignees_url"    : "https://api.github.com/repos/JohnJohnson/JohnsRepo/assignees{/user}",
                            "branches_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/branches{/branch}",
                            "tags_url"         : "https://api.github.com/repos/JohnJohnson/JohnsRepo/tags",
                            "blobs_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/git/blobs{/sha}",
                            "git_tags_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/git/tags{/sha}",
                            "git_refs_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/git/refs{/sha}",
                            "trees_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/git/trees{/sha}",
                            "statuses_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/statuses/{sha}",
                            "languages_url"    : "https://api.github.com/repos/JohnJohnson/JohnsRepo/languages",
                            "stargazers_url"   : "https://api.github.com/repos/JohnJohnson/JohnsRepo/stargazers",
                            "contributors_url" : "https://api.github.com/repos/JohnJohnson/JohnsRepo/contributors",
                            "subscribers_url"  : "https://api.github.com/repos/JohnJohnson/JohnsRepo/subscribers",
                            "subscription_url" : "https://api.github.com/repos/JohnJohnson/JohnsRepo/subscription",
                            "commits_url"      : "https://api.github.com/repos/JohnJohnson/JohnsRepo/commits{/sha}",
                            "git_commits_url"  : "https://api.github.com/repos/JohnJohnson/JohnsRepo/git/commits{/sha}",
                            "comments_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/comments{/number}",
                            "issue_comment_url": "https://api.github.com/repos/JohnJohnson/JohnsRepo/issues/comments{/number}",
                            "contents_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/contents/{+path}",
                            "compare_url"      : "https://api.github.com/repos/JohnJohnson/JohnsRepo/compare/{base}...{head}",
                            "merges_url"       : "https://api.github.com/repos/JohnJohnson/JohnsRepo/merges",
                            "archive_url"      : "https://api.github.com/repos/JohnJohnson/JohnsRepo/{archive_format}{/ref}",
                            "downloads_url"    : "https://api.github.com/repos/JohnJohnson/JohnsRepo/downloads",
                            "issues_url"       : "https://api.github.com/repos/JohnJohnson/JohnsRepo/issues{/number}",
                            "pulls_url"        : "https://api.github.com/repos/JohnJohnson/JohnsRepo/pulls{/number}",
                            "milestones_url"   : "https://api.github.com/repos/JohnJohnson/JohnsRepo/milestones{/number}",
                            "notifications_url": "https://api.github.com/repos/JohnJohnson/JohnsRepo/notifications{?since,all,participating}",
                            "labels_url"       : "https://api.github.com/repos/JohnJohnson/JohnsRepo/labels{/name}",
                            "releases_url"     : "https://api.github.com/repos/JohnJohnson/JohnsRepo/releases{/id}",
                            "deployments_url"  : "https://api.github.com/repos/JohnJohnson/JohnsRepo/deployments",
                            "created_at"       : "2016-09-22T11:25:05Z",
                            "updated_at"       : "2016-10-18T11:14:28Z",
                            "pushed_at"        : "2016-10-18T11:39:29Z",
                            "git_url"          : "git://github.com/JohnJohnson/JohnsRepo.git",
                            "ssh_url"          : "git@github.com:JohnJohnson/JohnsRepo.git",
                            "clone_url"        : "https://github.com/JohnJohnson/JohnsRepo.git",
                            "svn_url"          : "https://github.com/JohnJohnson/JohnsRepo",
                            "homepage"         : null,
                            "size"             : 4,
                            "stargazers_count" : 0,
                            "watchers_count"   : 0,
                            "language"         : null,
                            "has_issues"       : false,
                            "has_downloads"    : true,
                            "has_wiki"         : false,
                            "has_pages"        : false,
                            "forks_count"      : 0,
                            "mirror_url"       : null,
                            "open_issues_count": 1,
                            "forks"            : 0,
                            "open_issues"      : 1,
                            "watchers"         : 0,
                            "default_branch"   : "master"
                    ]
            ]
    ]
    static def emptyPullData = []
}