##The website title
name: Scrolls
##Markdown processor
markdown: kramdown
##syntax highlighter. change it to pygments
highlighter: pygments

##define base_url for valid usage in sitemap.xml and robots.txt
baseurl: scrolls
sass:
  sass_dir: _sass
  style: :compressed
#paginate: 5
#paginate_path: "page:num"
##The website description (to be used in meta tags)
description: The Automated Delivery Report Engine
##Some frequently used keywords on your website
keywords: devops, release, git, report, autoamtion, continuous delivery

##define this for disqus comment support
#disqus: forumname

##set this to enable google analytics
#ga_id: analyticsID
#ga_domain: analyticsDomain

##Some commonly used links
links:
  facebook: diabolab
  twitter: diabolab
  email: scrolls@diabol.se
  github: diabolab

##put desired image in img/ directory and set the value accordingly. If not defined, a placeholder image will be used.
about_image: placeholder.jpg
##comment this if you want full width posts with no sidebar
#sidebar: on
